local present, db = pcall(require, "dashboard")

if not present then
	return
end

-- uncomment only if you're using random headers or quotes
math.randomseed(os.time())

---@diagnostic disable-next-line: unused-local, unused-function
local function getRandomElement(t)
	return t[math.random(1, #t)]
end

local quotes = {
	"Beautiful is better than ugly",
	"Explicit is better than implicit",
	"Simple is better than complex",
	"Complex is better than complicated",
	"Flat is better than nested",
	"Readability counts",
	"Practicality beats purity",
	"Errors should never pass silently, Unless explicitly silenced",
	"In the face of ambiguity, refuse the temptation to guess",
	"If the implementation is hard to explain, it's a bad idea",
	"If the implementation is easy to explain, it may be a good idea",
	"Keep Calm and Enjoy Coding",
	"RTFM",
	"Code Never Lies, Comments Sometimes Do",
	"If you don't walk today, you'll have to run run tomorrow",
	"Coding Like Poetry Should Be Short and Concise",
	"First, Solve the Problem. Then, Write the Code",
	"Code Is Like Humor. When You Have to Explain It, It's Bad",
	"Make It Work, Make It Right, Make It Fast",
	"Clean Code Always Looks Like It Was Written by Someone Who Cares",
	"Programming Is Learned by Writing Programs",
	"Good Programmers Write Code That Humans Can Understand",
	"In Order to Be Irreplaceable, One Must Always Be Different",
	"Fix the Cause, Not the Symptom",
	"Simplicity Is the Soul of Efficiency",
	"Before Software Can Be Reusable It First Has to Be Usable",
	"Simplicity Is the Ultimate Sophistication",
	"Do or Do Not, There Is No Try",
	"Code Like a Craftsman, Ship Like an Engineer",
	"Read the Documentation, Then Write the Code",
	"Always Leave the Codebase Better Than You Found It",
	"Think Twice, Code Once",
	"The Only Way to Go Fast Is to Go Well",
	"If It Works, It's Not Done",
	"Code with Passion, Change the World",
	"Refactor Early, Refactor Often",
	"Programming Isn't About What You Know; It's About What You Can Figure Out",
	"Premature Optimization Is the Root of All Evil",
	"The Best Way to Predict the Future Is to Invent It",
	"The Function of Good Software Is to Make the Complex Appear to Be Simple",
	"Keep Calm and Debug On",
	"Think Globally, Code Locally",
	"Code with Purpose, Not Just for the Sake of It",
	"Stay Curious, Keep Learning",
	"Code Is Power, Use It Wisely",
	"Embrace the Challenge, Conquer the Code",
	"Don't Just Write Code, Solve Problems",
	"Code Is the Closest Thing We Have to Magic",
	"Great Coders Are Born of Great Debugging Skills",
	"The Best Code Is the One That Never Needs to Be Written",
	"Coding Is a Journey, Not a Destination",
	"Code Elegantly, Think Pragmatically",
	"Coding Is an Art, and You Are the Artist",
	"Learn from Your Bugs, They Make You a Better Developer",
	"Code Like You're Explaining It to Your Future Self",
	"Code as If Someone Else Will Maintain Your Work",
	"Stay Patient, Code Will Reveal Its Secrets",
	"Code Is the Language of Possibilities",
	"The More You Code, the Luckier You Get",
	"Coding Is the Ultimate Form of Self-Expression",
	"Dream Big, Code Bigger",
	"You Can't Learn Anything From the Things You Already Know",
	"The Magic Key to Productivity and Growth Is Simplicity",
	"Programming Is Not About Typing, It's About Thinking",
	"Just Dive In and Start Solving It",
	"The Code You Write Makes You a Programmer",
	"The Code You Delete Makes You a Good Programmer",
	"The Code You Don't Have to Write Makes You a Great Programmer",
	"Focused, Hard Work Is the Real Key to Success",
	-- "Keep Your Eyes On the Goal, and Just Keep Taking the Next Step Towards Completing It",
	"Keep Your Eye On the Prize and Take One Step At a Time",
	-- "If You Aren't Sure Which Way to Do Something, Do It Both Ways and See Which Works Better",
	"Explore Multiple Paths to Find the Optimal Way",
	"The Most Important Thing Is to Write Code",
	"You Have to Actually Write Code to Become a Proficient Programmer",
	-- "If You Don't Understand something, Break It Down Into Smaller Parts, and Understand Each Part",
	"Divide and Conquer to Understand",
	"Good Code Is Short, Simple, and Symmetrical",
	"Make Things Clearer, More Understandable, and Easier to Work With",
	"Being a Good Programmer Is About How Well You Can Think and Solve Problems",
	"Write Code That Is Easy to Read and Understand",
	"Programming Is About Creating Elegant and Efficient Solutions",
	"Don't Be Afraid to Throw Away Code and Start Over",
	"Read and Understand Other People's Code, Learn From the Masters",
	"Stop Asking; Just go do something",
}

-- source: https://emojicombos.com/
local headers = {
	{
		[[⠀⠀⠀⠀⠀⠀⠀⣀⣤⣴⣶⣶⣶⣿⣿⣿⣷⣶⣶⣶⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡀⠀⠀⠀⠀]],
		[[⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀]],
		[[⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀]],
		[[⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀]],
		[[⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇]],
		[[⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]],
		[[⣿⣿⡏⠉⠙⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠋⠉⠉⣿⣿]],
		[[⢻⣿⡇⠀⠀⠀⠈⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀⠀⢀⣿⡇]],
		[[⠘⣿⣷⡀⠀⠀⠀⠀⠀⠀⠉⠛⠿⢿⣿⣿⣿⠿⠛⠋⠀⠀⠀⠀⠀⠀⢀⣼⣿⠃]],
		[[⠀⠹⣿⣿⣶⣦⣤⣀⣀⣀⣀⣀⣤⣶⠟⡿⣷⣦⣄⣀⣀⣀⣠⣤⣤⣶⣿⣿⡟⠀]],
		[[⠀⠀⣨⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⡇⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀]],
		[[⠀⢈⣿⣿⣿⣿⣿⡿⠿⠿⣿⣿⣷⠀⣼⣷⠀⣸⣿⣿⣿⡿⠿⠿⠿⣿⣿⣿⡇⠀]],
		[[⠀⠘⣿⣿⣿⡟⠋⠀⠀⠰⣿⣿⣿⣷⣿⣿⣷⣿⣿⣿⣿⡇⠀⠀⠀⣿⣿⠟⠁⠀]],
		[[⠀⠀⠈⠉⠈  ⠀⠀⠘⣿⣿⢿⣿⣿⢻⣿⡏⣻⣿⣿⠃⠀⠀⠀⠈⠁⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⣿⣿⢸⣿⡇⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⡇⣿⣿⢸⣿⡇⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⣿⣿⢸⣿⡇⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⣿⣿⢸⣿⠃⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡇⣿⣿⢸⣿⠀⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠿⠇⢿⡿⢸⡿⠀⠿⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[                              ]],
		[[     WE ARE NOT YOUR KIND     ]],
		[[                              ]],
	},
	{
		[[                                     ]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⢹⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⢻⡾⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⢸⣼⠁⠀⠀⠄⠹⣿⣆⠀⠀⡰⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠐⡀⠀⠀⠸⡄⢠⡿⠀⠀⣺⣿⢾⠀⠘⣿⣧⣼⠀⠀⠀⡰⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠐⢄⠀⠀⠀⢳⡀⣦⣹⣥⠆⠀⠀⠀⠈⠈⢀⠀⠈⣿⣷⡎⣰⠇⠀⠀⠀⠔⠀⠀⠀⠀⠀]],
		[[⠀⠀⢀⠀⠀⠀⠈⠳⣄⢳⣼⣿⣿⠁⢀⣠⣲⣾⣿⣿⣾⣷⣦⡀⢿⣿⣴⢋⣤⠋⠀⠀⠀⢀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠉⠲⣤⡙⣶⣿⣿⡿⠀⠀⠀⠀⠀⢀⡀⢠⡠⠄⠀⠀⠀⢹⣿⣿⡞⣡⣴⠚⠁⠀⠀⠀⠀]],
		[[⠀⠈⠒⠦⣤⣈⣻⣿⣿⣿⠏⠀⢀⢴⣾⣿⣿⡿⠿⠿⠿⣿⣽⣿⠦⠀⠹⣿⣿⣾⣋⣠⡤⠖⠂⠁⠀]],
		[[⡀⠀⠀⡀⠒⠶⣾⣿⣿⠃⢀⣤⠟⠉⠀⠀⣠⣤⠀⠀⠀⠀⠀⠀⠀⠑⠀⠘⣿⢿⡶⠖⢀⠀⠀⠀⡀]],
		[[⠀⠀⠀⠤⠤⣤⣿⡿⠀⠐⠀⢠⣶⡄⡀⣆⠸⠿⠀⠀⠀⢰⣸⡇⣾⣆⠀⠀⠀⣿⣷⣤⠤⠄⠀⠀⠀]],
		[[⠒⠂⠉⠉⢹⣿⡟⢀⠤⠀⣼⣿⣿⣿⣆⠻⣯⣶⡶⠶⣿⡽⢋⣾⣿⡿⢀⣴⠇⠀⠿⢿⡉⠉⠉⠐⠂]],
		[[⠀⠀⣀⣴⣿⠏⠀⠀⢤⣛⣶⣤⣍⣿⣿⣿⣿⣶⣶⣶⣾⣿⣿⣷⣿⣋⣴⣨⣖⡀⠀⠀⠸⣄⡀⠀⠀]],
		[[⠀⢀⣾⢿⠃⠀⠀⠀⠼⡿⣷⣼⣧⣾⣦⢿⣿⣭⣭⣭⡴⠖⣻⣿⠶⢟⣉⣭⣶⠢⠄⠀⠀⠈⣦⠀⠀]],
		[[⣠⠿⠟⠀⠀⠀⠀⠀⠀⢀⣀⣀⣠⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⡀⣷⠀]],
		[[⠀⠀⠈⠈⢈⠜⠉⠉⠉⣸⠋⣼⢡⡟⣿⣿⢿⣿⣿⣿⣿⡿⡟⣿⠹⡌⢻⡀⠁⠀⠙⢄⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⢀⠊⠀⠀⢠⠏⠰⠀⡿⢸⠀⡇⢸⠈⣇⠸⠀⢷⠀⠀⠈⢦⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠃⠀⠀⢰⠀⠀⠀⡇⠀⠀⢸⠀⠀⠀⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠂⠀⠀⠀⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀ ⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[             MEMENTO MORI            ]],
		[[            MEMENTO VIVERE           ]],
		[[                                     ]],
	},
	{
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⠋⣿⡍⢿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡿⠁⠀⣿⠇⠈⢿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡿⠁⠀⠀⣿⡇⠀⠀⢻⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡟⠀⠀⠀⠀⣿⡆⠀⠀⠀⠻⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⠟⠀⢀⣀⣤⣤⣿⣥⣤⣀⣀⠀⠹⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣏⣴⣾⠿⠟⠛⠙⣿⡏⠛⠻⠿⣷⣦⣝⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⠟⠁⠀⠀⠀⠀⣿⡅⠀⠀⠀⠈⠙⢿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⣿⡅⠀⠀⠀⠀⠀⠈⢿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⣿⡅⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⠀⠀⣼⡿⢻⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⣿⡆⠀⠀⠀⠀⠀⠀⠀⢸⣿⡏⢿⣧⡀⠀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⠀⢀⣼⡿⠁⢸⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⣿⠆⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⠈⢻⣷⡀⠀⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⠀⢀⣾⡟⠁⠀⠈⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⣿⠇⠀⠀⠀⠀⠀⠀⠀⣸⣿⠃⠀⠀⢻⣷⡄⠀⠀⠀⠀⠀]],
		[[⠀⠀⠀⠀⢠⣿⠟⠀⠀⠀⠀⠸⣿⣇⠀⠀⠀⠀⠀⠀⠀⣿⡃⠀⠀⠀⠀⠀⠀⣰⣿⠏⠀⠀⠀⠀⠹⣿⡄⠀⠀⠀⠀]],
		[[⠀⠀⠀⣠⣿⠏⠀⠀⠀⠀⠀⠀⠘⢿⣷⣄⠀⠀⠀⠀⠀⣿⡃⠀⠀⠀⠀⣠⣾⡿⠋⠀⠀⠀⠀⠀⠀⠙⣿⣆⠀⠀⠀]],
		[[⠀⠀⢠⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣄⣀⡀⠀⣿⠇⠀⣀⣠⣼⣿⠟⠃⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣄⠀⠀]],
		[[⠀⣴⣿⣯⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣭⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣽⣿⣧⠀]],
		[[⠐⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠂]],
		[[            FOR THE GREATER GOOD           ]],
		[[                                           ]],
	},
}

db.setup({
	theme = "doom", -- hyper
	config = {
		header = headers[2],
		center = {
			{
				icon = "🗓 ",
				desc = "Calendar                                          ",
				action = ":Calendar",
				key = "c",
			},
			{
				icon = "📓 ",
				desc = "Open Wiki                                         ",
				action = "VimwikiIndex",
				key = "w",
			},
			{
				icon = "🗃 ",
				desc = "Browse Directories                                ",
				-- action = "Telescope file_browser cwd=" .. home,
				action = "Telescope file_browser",
				key = "d",
			},
			{
				icon = "🗄 ",
				desc = "Find File                                         ",
				-- action = "Telescope find_files find_command=rg,--hidden,--files",
				action = "Telescope find_files",
				key = "f",
			},
			{
				icon = "💼 ",
				desc = "Recent Files                                      ",
				action = "Telescope oldfiles",
				key = "r",
			},
			{
				icon = "🔌 ",
				desc = "Manage Plugins                                    ",
				action = "Lazy",
				key = "p",
			},
			{
				icon = "🚀 ",
				desc = "Manage LSP/Formatters/...                         ",
				action = "Mason",
				key = "m",
			},
		},
		footer = { "👑 " .. getRandomElement(quotes) .. " 👑" },
	},
})
