nnoremap <space>ff :Files<CR>
nnoremap <space>fg :Rg<CR>
nnoremap <space>fc :Colors<CR>
nnoremap <space>fC :Commands<CR>
nnoremap <space>fb :Buffers<CR>
nnoremap <space>fw :Windows<CR>
nnoremap <space>fpt :Tags<CR>
nnoremap <space>fbt :BTags<CR>
nnoremap <space>fh :History<CR>
nnoremap <space>fm :Marks<CR>
