let @b='cmake --build ./build'
let @c='cmake --build ./build -t clean'
let @f='cmake --build ./build --clean-first'
let @g='cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
let @i='cmake --install ./build'
let @r='cd ./build/bin/ && ./prog && cd ../../ > /dev/null 2>&1'
let @t='cd ./build && ctest --schedule-random --output-on-failure && cd - > /dev/null 2>&1'
